version: "3"

services:
  mongo:
    image: mongo # https://hub.docker.com/_/mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - nest-database

  mongo-express:
    image: mongo-express # https://hub.docker.com/_/mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    ports:
      - 8081:8081
    networks:
      - nest-database

networks:
  nest-database:
    driver: bridge